modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL=""
license="#LICENSE"
[[mods]]
    modId="#MODID"
    version="1.0"
    displayName="#NAME"
    description="#DESC"
	authors="#AUTHOR"
	logoFile="pack.png"